version: "3"
services:
  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ${SENSOR_METRICS_FILE_PATH}:/var/tmp/metrics.json:ro
    depends_on:
      - influxdb
      - grafana
    environment:
      INFLUXDB_URL: http://influxdb:8086
    networks:
      - influxdb_net
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    networks:
      - influxdb_net
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      INFLUXDB_HTTP_BIND_ADDRESS: 0.0.0.0:8086
    networks:
        - influxdb_net

networks:
  influxdb_net: